version: "3.3"
   
services:
  db_crm:
    restart: always
    container_name: db_crm
    build:
      context: ./
      dockerfile: db.Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - api-network
    ports:
      - "5432:5432"

  api_crm:
    container_name: api_crm
    build:
      context: ./
      dockerfile: api.Dockerfile
    networks:
      - api-network
    ports:
      - "8081:8080"
    links:
      - db_crm
    depends_on:
      - db_crm

networks:
  api-network:

volumes:
  db-data: